name: "ZOAU-Node Bug report"
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    attributes:
      label: Node.js Version
      description: Output of `node -v`
  - type: input
    attributes:
      label: ZOAU version
      description: |
        output of `zoaversion`
  - type: input
    attributes:
      label: zoau-node version
      description: |
        version of zoau-node installed
  - type: input
    attributes:
      label: Platform
      description: |
        output of `uname -a`
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: Enter details about your bug, preferably a simple code snippet.
  - type: textarea
    attributes:
      label: How often does it reproduce? Is there a required condition?
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible please provide textual output instead of screenshots.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible please provide textual output instead of screenshots.
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
